apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemoncontainos-deploy
  labels:
    app: daemoncontainos-app
  annotations:
spec:
  selector:
    matchLabels:
      app: daemoncontainos-app
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: daemoncontainos-app
    spec:
      containers:
      - name: daemoncontainos-app
        image: snrmukesh/daemon_containos:1.0.0
        imagePullPolicy: Always
        env:
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"