apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcontainos-deploy
  labels:
    app: webcontainos-app
  annotations:
spec:
  selector:
    matchLabels:
      app: webcontainos-app
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  template:
    metadata:
      labels:
        app: webcontainos-app
    spec:
      containers:
      - name: webcontainos-app
        image: snrmukesh/containos:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: REDIS_HOST
            value: redis-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-service
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: PGPASSWORD
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"